# Generated by Django 3.2.13 on 2022-04-11 17:19

from django.db import migrations, models
import multiple_choices

class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False,
                                           verbose_name='ID')),
                ('likes',
                 multiple_choices.MultipleChoiceModelField(
                     required=True, choices=[(0, 'Pizza'), (1, 'Juice'), (2, 'Beef'), (3, 'Orange juice'),
                                             (4, 'Milk')])),
            ],
        ),
    ]
